name: kita
version: '0.5.5'
summary: Japanese learning tool
description: |
  A simple tool to help Japanese language learners.

confinement: strict
base: core18
grade: stable
license: GPL-3.0+

parts:
  kita:
    source: .
    plugin: ruby
    gems:
      - kita
    ruby-version: 2.7.0
    stage-packages:
      - gobject-introspection
      - gir1.2-atk-1.0
      - gir1.2-atspi-2.0
      - gir1.2-freedesktop
      - gir1.2-gdkpixbuf-2.0
      - gir1.2-glib-2.0
      - gir1.2-gtk-3.0
      - gir1.2-pango-1.0
      - libcanberra-gtk3-0
      - libgstreamer1.0-0
      - libglib2.0-0
      - libgirepository-1.0-1
      - gir1.2-gstreamer-1.0
      - gstreamer1.0-plugins-base
      # Just trying these to see if it makes sound work
      - libpulse0
      - libpulse-mainloop-glib0
      - libslang2
      - libgpm2
      - libasound2

apps:
  kita:
    command: bin/kita
    extensions: [gnome-3-28]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - x11
      - audio-playback
      - home
    slots:
      - dbus-daemon
    common-id: uk.danbishop.kita

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: uk.danbishop.kita
