name: kita
version: '0.9.3'
summary: Japanese learning tool
description: |
  A simple tool to help Japanese language learners.

confinement: strict
base: core18
grade: stable
license: GPL-3.0+

parts:
  kita:
    source: .
    plugin: ruby
    gems:
      - kita
    ruby-version: 2.7.1
    stage-packages:
      - libgstreamer1.0-0
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - libslang2
      - libgpm2
      # - freeglut3
      # - libglu1-mesa
      - libgirepository-1.0-1
      - gir1.2-gstreamer-1.0

apps:
  kita:
    command: bin/kita
    extensions: [gnome-3-28]
    plugs:
      - audio-playback
    slots:
      - dbus-daemon
    common-id: uk.danbishop.kita

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: uk.danbishop.kita
